USE myHotel
ALTER TABLE Employees WITH CHECK
ADD CONSTRAINT FK_JobID FOREIGN KEY(JobID) REFERENCES Jobs(JobID)
ON UPDATE CASCADE
GO
ALTER TABLE Employees WITH CHECK
ADD CONSTRAINT FK_EHotelID FOREIGN KEY(HotelID) References Hotels(HotelID)
ON UPDATE CASCADE
GO
ALTER TABLE Guests WITH CHECK
ADD CONSTRAINT FK_GZipID FOREIGN KEY(ZipID) References Zipcode(ZipID)
ON UPDATE CASCADE
GO
ALTER TABLE Reservations WITH CHECK
ADD CONSTRAINT FK_GuestID FOREIGN KEY(GuestID) References Guests(GuestID)
ON UPDATE CASCADE
GO
ALTER TABLE Reservations WITH CHECK
ADD CONSTRAINT FK_RHotelID FOREIGN KEY(HotelID) References Hotels(HotelID)
ON UPDATE CASCADE
GO
ALTER TABLE Hotels WITH CHECK
ADD CONSTRAINT FK_HZipID FOREIGN KEY(ZipID) References Zipcode(ZipID)
ON UPDATE CASCADE